export const SET_USER = 'SET_USER';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const FETCH_PROFILE_INFO = 'FETCH_PROFILE_INFO';
export const FETCH_CONTACTS= 'FETCH_CONTACTS';
export const FETCH_PHONE= 'FETCH_PHONE';
export const FETCH_EMAIL= 'FETCH_EMAIL';
export const FETCH_ACCESS_TOKEN = 'FETCH_ACCESS_TOKEN';
